Render:
  MaxHorizontalSkipPixels: 8
  EarlyExitMultiplier: 4.0
  SafetyFactor: 0.9
  DetailMultiplier: 1.5
  DZGuard: 1e-300

Window:
  Width: 600
  Height: 600

Fractal:
  MaxIterations: 500
  InitialZoom: 1.0
  InitialOffsetX: -0.5
  InitialOffsetY: 0.0